version: "3.9"

services:
  warp-unlimited:
    image: ghcr.io/thecaduceus/wla:master
    container_name: warp-unlimited
    environment:
      - WARP_ID=${WARP_ID}
    ports:
      - 8080:8080
    restart: unless-stopped
